.PHONY: all clean print

all: clean c01 c02 c03 c04 c05 c06 c07 c08 c09 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 c21 c22 

ex05: c05
	java ex05.Algebra;

ex11: c11
	java ex11.Substring;

c01:
	javac ex01/Palindromo.java;

c02:
	gcc ex02/palindromo.c -o ex02/exec;

c03:
	javac ex03/Ex03.java;

c04:
	javac ex04/Alteracao.java;

c05:
	javac ex05/Algebra.java;

c06:
	javac ex06/Is.java;

c07:
	javac ex07/Inversao.java;

c08:
	javac ex08/Soma.java;

c09:
	javac ex09/Anagrama.java;

c10:
	javac ex10/Contagem.java;

c11:
	javac ex11/Substring.java;

c12:
	javac ex12/Senha.java;

c13:
	javac ex13/Leitura.java;

c14:
	javac ex14/Arquivo.java;

c15:
	gcc ex15/file.c -o ex15/exec;

c16:
	javac ex16/PalindromoRec.java;

c17:
	gcc ex17/palindromorec.c -o ex17/exec;

c18:
	javac ex18/CiframentoRec.java;

c19:
	javac ex19/AlgebraRec.java;

c20:
	javac ex20/IsRec.java;

c21:
	gcc ex21/inversao.c -o ex21/exec;

c22:
	gcc ex22/somarec.c -o ex22/exec;

clean:
	rm ex01/Palindromo.class;
	rm ex02/exec;
	rm ex03/Ex03.class;
	rm ex04/Alteracao.class;
	rm ex05/Algebra.class;
	rm ex06/Is.class;
	rm ex07/Inversao.class;
	rm ex08/Soma.class;
	rm ex09/Anagrama.class;
	rm ex10/Contagem.class;
	rm ex11/Substring.class;
	rm ex12/Senha.class;
	rm ex13/Leitura.class;
	rm ex14/Arquivo.class;
	rm ex15/exec;
	rm ex16/PalindromoRec.class;
	rm ex17/exec;
	rm ex18/CiframentoRec.class;
	rm ex19/AlgebraRec.class;
	rm ex20/IsRec.class;
	rm ex21/exec;
	rm ex22/exec;

	
